### ISSUE TITLE
Android Application_Id

### ISSUE THREAD

**Issue by K232** [marcojak/MTAdmob#1]
I'm trying to add your package to my app. According to your description, I need to add this line to AndroidManifest:

```
 <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
```
The ca-app-pub is probably the same as I entered already in MobileAds.Initialize, but what is the APPLICATION_ID ? I also checked your [Sample AndroidManifest.xml](https://github.com/marcojak/MTAdmob/blob/master/Sample/SampleMTAdmob.Android/Properties/AndroidManifest.xml) but did not find the key there?

**Comment by marcojak** [comment]
Hi,
This help will tell you hoe to get the APP Id of your apps:
https://support.google.com/admob/answer/7356431?hl=en

You don't have to change this line: com.google.android.gms.ads.APPLICATION_ID
You have just to insert the correct Android:value

I hope this helps you, otherwise let me know.
