### ISSUE TITLE
How to show interstitials

### ISSUE THREAD

**Issue by K232** [marcojak/MTAdmob#10]
HI Marco,
to show interstitials there are 2 lines of code:

- CrossMTAdmob.Current.LoadInterstitial("xx-xxx-xxx-xxxxxxxxxxxxxxxxx/xxxxxxxxxx");
- CrossMTAdmob.Current.ShowInterstitial();

As seen in your sample, ShowInterstitial does not work as long as LoadInterstitial is not called and completed. So what would be the proposed usage within an app? Typically I just want to say "ShowInterstitial" and that's it, as shown in your [linked blog post](https://www.xamarinexpert.it/admob-made-easy/). But that's not working, as ShowInterstitial does not take any parameters anymore.

So what's the proposed way then? 
- Subscribe to OnInterstitialLoaded on my Page
- LoadInterstitial
- Within OnInterstitialLoaded, call ShowInterstitial
- Unsubscribe from OnInterstitialLoaded as soon as I leave my page

Is that the best way to do it?

**Comment by marcojak** [comment]
Hi Kai,

Yes, you need to preload the Interstitial before showing it.
When to show it then, it up to you. 
You can show it immediately when you receive the event OnInterstitialLoaded or you can preload it and then show it only when required.

You are correct about subscribe and unsubscribe, it's a good thing to do it when you load a page and when you leave it.

**Comment by K232** [comment]
OK, thanks for clarification! 👍
Maybe it would bei a Feature Request to have that included in the package, in Addition to current Options? Something Like "ShowIfLoaded"? So i could load it, and wegen the User clicks a Button i could Show the interstitial If it is loaded?

**Comment by marcojak** [comment]
It's already there.

bool IsInterstitialLoaded();

this will tell you if the Interstitial is ready to be used

**Comment by K232** [comment]
Many thanks Marco!
