### ISSUE TITLE
Rewarded video doesn't work on iOS

### ISSUE THREAD

**Issue by prok155** [marcojak/MTAdmob#111]
**Describe the bug**
I updated plugin from 1.6.9 to the 1.8.0 version. When I complete rewarded video in 1.8.0 version I don't get reward, it happens only on iOS. When I used 1.6.9 version, everything works as expected.

**To Reproduce**
1. Watch rewarded video and complete it.
2. You won't get the reward, seems like OnRewardedVideoAdCompleted is not triggered.

**Expected behavior**
You should get the reward when you complete rewarded video.

**Smartphone (please complete the following information):**
 - OS: iOS
 - Version 1.8.0

**Comment by changguangyu** [comment]
Same issue here, not onley OnRewardedVideoAdCompleted , all callback event is not triggered under iOS when using 1.8.0

**Comment by marcojak** [comment]
Please use version 1.9.x.x. It should fix the issue
