### ISSUE TITLE
PendingIntent issue with Android 13

### ISSUE THREAD

**Issue by AlanFloyd** [marcojak/MTAdmob#112]
Hello,

I don't know if you use PendingIntent. But since updating my device to Android 13 I am getting this error:

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

Thanks for your help
Greetings
Dietmar

**Comment by dylix** [comment]
I'd be interested in this as well. With the deadline of November 1, 2022, apps depending on this project will be unable to release new versions/install on new devices

**Comment by prok155** [comment]
Check #89 , there is a solution how to fix this issue
