### ISSUE TITLE
To get ads on test device

### ISSUE THREAD

**Issue by ablohme86** [marcojak/MTAdmob#116]
Hello, I am not getting any ads on my simulator, but I get this message in the debugger:

Google> To get test ads on this device, set: 
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]

How do I add that in Xamarin?

**Comment by ablohme86** [comment]
I know, but when I try to add: CrossMTAdmob.Current.TestDevices.Add("74cf080f8ed2859a3124e22100f82ed6");

but it gives me an exception:
<img width="1143" alt="Screenshot 2022-11-01 at 23 17 19" src="https://user-images.githubusercontent.com/17109732/199352498-0f6a7490-1ee0-4742-8b20-716d1a370447.png">


<img width="815" alt="Screenshot 2022-11-01 at 23 16 06" src="https://user-images.githubusercontent.com/17109732/199352514-f72aff5f-3b7f-4356-b023-8e65018491e3.png">

**Comment by marcojak** [comment]
TestDevices= new List...

You are adding strings without initialising the list!
