### ISSUE TITLE
CrossMTAdmob.Current.OnInterstitialLoaded listetning on iOS

### ISSUE THREAD

**Issue by ablohme86** [marcojak/MTAdmob#117]
After putting: 

                CrossMTAdmob.Current.OnInterstitialLoaded += Current_OnInterstitialLoaded1;
 
on iOS in App.xaml.cs at the OnStart override it will never "flip". Works great on Android, so its hard for me to know when to call .Show. If I create a button to call ShowInstertitial and click it after load I will receive a interstitial ad

Banner ads is working on both iOS and Android

**Comment by marcojak** [comment]
Version 1.9 should work fine.
Closing for now.
