### ISSUE TITLE
Xamarin.Google.iOS.SignIn still necessary?

### ISSUE THREAD

**Issue by K232** [marcojak/MTAdmob#12]
With Xamarin.Google.iOS.SignIn 4.4.0, I was not able to upload the ipa to Apple. I always get the following error message:

> Dear Developer,
> 
> We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
> 
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
> 
> Best regards,
> 
> The App Store Team

I've added the mtouch parameter as described by Gerald in [UIWebView Deprecation and Xamarin.Forms](https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/), but I still got this message :-( 

I've tried to use latest Xamarin.Google.iOS.SignIn 5.0.2.1 but got several errors during compiling. So I've completely removed Xamarin.Google.iOS.SignIn from my iOS project. And app compiles fine and ads are displayed (as far as I see). Is there any reason to install Xamarin.Google.iOS.SignIn in the iOS project? It's described in your linked blog article at [https://www.xamarinexpert.it/admob-made-easy/](https://www.xamarinexpert.it/admob-made-easy/) e.g. in section "iOS Project (Important)" so I've added it. Maybe it's not necessary anymore? If so, is Xamarin.Google.iOS.MobileAds still necessary to add manually? I've currently latest 7.57.0 in use and it works fine.

Many thanks!

**Comment by marcojak** [comment]
You don't need to add any of them anymore.
It's all done automatically.
You can see in the sample directory the test project, there is no reference anymore to the other packages.

I've updated the readme to remove the part regarding the 2 packages.

I'd suggest you to remove all the packages and just keep MTAdmob (in case, remove it as well and reinstall it). Remember to clean the project, remove the bin and obj folders and everything should be fine.
