### ISSUE TITLE
error MarcTron.Admob, APP CRASH

### ISSUE THREAD

**Issue by grodryq** [marcojak/MTAdmob#124]
I monetize my app with the nugets MarcTron.Admob, however, since I updated my application, it crashes, sometimes it does not open, sometimes it does not pass SPLASH and sometimes I get this error "Targeting S+ requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE...".

 I am using:
Android target version >12 or API level >31.
Visual Studio for Windows
Operating System Windows 10
Xamarin.Forms Version 5.0.0.2478
MarcTron.Admob 1.9.0.0.3

**Comment by grodryq** [comment]
[App2.zip](https://github.com/marcojak/MTAdmob/files/10287212/App2.zip)

see de example plis

**Comment by marcojak** [comment]
Hi.
To solve this problem, have a look at this: https://github.com/marcojak/MTAdmob/issues/89

I'll add this to the readme.

I'm closing it for now but feel free to open it again if it's not solved.
