### ISSUE TITLE
App crashes during App Store review

### ISSUE THREAD

**Issue by BillyMartin1964** [marcojak/MTAdmob#125]
**I can't replicate the crash, but App Store has rejected it twice for the same crash:**

Incident Identifier: C46C84FE-9579-4D52-B827-2B7D3906507F
CrashReporter Key:   e8514feb1b03564f681a58ec6a0110fd1f89e826
Hardware Model:      iPad11,3
Process:             Yatzy.iOS [1671]
Path:                /private/var/containers/Bundle/Application/25DB4695-B7AF-4277-9E2B-4F16DB576C86/Yatzy.iOS.app/Yatzy.iOS
Identifier:          com.sitesculptors.Yatzy
Version:             2.4 (2.4)
AppStoreTools:       14C17
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.sitesculptors.Yatzy [1003]

Date/Time:           2022-12-28 17:30:26.8003 -0800
Launch Time:         2022-12-28 17:30:26.3474 -0800
OS Version:          iPhone OS 16.2 (20C65)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Application Specific Information:
abort() called

Thread 0 name:  tid_103 Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1cbba1160 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1dc1fc1ac pthread_kill + 268
2   libsystem_c.dylib             	       0x196154c8c abort + 180
3   Yatzy.iOS                     	       0x106f9b448 xamarin_find_protocol_wrapper_type + 0
4   Yatzy.iOS                     	       0x106e61d58 gc.safepoint_poll + 37241672
5   Yatzy.iOS                     	       0x106df6e50 gc.safepoint_poll + 36803648
6   Yatzy.iOS                     	       0x106df7828 gc.safepoint_poll + 36806168
7   Yatzy.iOS                     	       0x106deb674 gc.safepoint_poll + 36756580
8   Yatzy.iOS                     	       0x104bd1058 gc.safepoint_poll + 996936
9   Yatzy.iOS                     	       0x104f4ddb0 gc.safepoint_poll + 4653984
10  Yatzy.iOS                     	       0x106e08c14 gc.safepoint_poll + 36876804
11  Yatzy.iOS                     	       0x106ec2860 gc.safepoint_poll + 37637712
12  Yatzy.iOS                     	       0x106ec60a0 gc.safepoint_poll + 37652112
13  Yatzy.iOS                     	       0x104a82e20 GADInlineAdaptiveBannerAdSizeWithWidthAndMaxHeight + 633260
14  Yatzy.iOS                     	       0x104a8335c GADInlineAdaptiveBannerAdSizeWithWidthAndMaxHeight + 634600
15  Foundation                    	       0x188f10850 __NSThreadPerformPerform + 264
16  CoreFoundation                	       0x18ebadf34 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
17  CoreFoundation                	       0x18ebba30c __CFRunLoopDoSource0 + 176
18  CoreFoundation                	       0x18eb3e230 __CFRunLoopDoSources0 + 340
19  CoreFoundation                	       0x18eb53b8c __CFRunLoopRun + 836
20  CoreFoundation                	       0x18eb58ec0 CFRunLoopRunSpecific + 612
21  GraphicsServices              	       0x1c8303368 GSEventRunModal + 164
22  UIKitCore                     	       0x19104e86c -[UIApplication _run] + 888
23  UIKitCore                     	       0x19104e4d0 UIApplicationMain + 340
24  Yatzy.iOS                     	       0x106f8f9e0 xamarin_UIApplicationMain + 24
25  Yatzy.iOS                     	       0x104ef804c gc.safepoint_poll + 4302396
26  Yatzy.iOS                     	       0x104f7da78 gc.safepoint_poll + 4849768
27  Yatzy.iOS                     	       0x106e08c14 gc.safepoint_poll + 36876804
28  Yatzy.iOS                     	       0x106ec2860 gc.safepoint_poll + 37637712
29  Yatzy.iOS                     	       0x106ec8b68 gc.safepoint_poll + 37663064
30  Yatzy.iOS                     	       0x106de6f24 gc.safepoint_poll + 36738324
31  Yatzy.iOS                     	       0x106fa3da4 xamarin_log + 6012
32  Yatzy.iOS                     	       0x104add6c4 GADInlineAdaptiveBannerAdSizeWithWidthAndMaxHeight + 1004112
33  dyld                          	       0x1ad36a960 start + 2528

Thread 1:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 3 name:  SGen worker
Thread 3:
0   libsystem_kernel.dylib        	       0x1cbb9b37c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1dc1fd06c _pthread_cond_wait + 1232
2   Yatzy.iOS                     	       0x106f65a88 gc.safepoint_poll + 38305912
3   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 4 name:  Finalizer
Thread 4:
0   libsystem_kernel.dylib        	       0x1cbb9aa24 semaphore_wait_trap + 8
1   Yatzy.iOS                     	       0x106e65160 gc.safepoint_poll + 37254992
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 5:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 6 name:  com.apple.uikit.eventfetch-thread
Thread 6:
0   libsystem_kernel.dylib        	       0x1cbb9aaa8 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1cbbacfc4 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1cbbad204 mach_msg_overwrite + 388
3   libsystem_kernel.dylib        	       0x1cbb9afec mach_msg + 24
4   CoreFoundation                	       0x18eb52ad4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x18eb53d18 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x18eb58ec0 CFRunLoopRunSpecific + 612
7   Foundation                    	       0x188f170d4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                    	       0x188f16fbc -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9   UIKitCore                     	       0x19118372c -[UIEventFetcher threadMain] + 436
10  Foundation                    	       0x188f305a8 __NSThread__start__ + 716
11  libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
12  libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 7:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 9 name:  tid_7c03
Thread 9:
0   libsystem_kernel.dylib        	       0x1cbb9b37c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1dc1fd06c _pthread_cond_wait + 1232
2   Yatzy.iOS                     	       0x106f75004 gc.safepoint_poll + 38368756
3   Yatzy.iOS                     	       0x106f7dd6c gc.safepoint_poll + 38404956
4   Yatzy.iOS                     	       0x106f04564 gc.safepoint_poll + 37907284
5   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
6   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
7   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 10 name:  Thread Pool Worker
Thread 10:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 11 name:  Thread Pool Worker
Thread 11:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 12:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 19 name:   Dispatch queue: APMExperimentWorkerQueue
Thread 19:
0   libsqlite3.dylib              	       0x1b2b6cb94 0x1b2a8e000 + 912276
1   libsqlite3.dylib              	       0x1b2a9b890 0x1b2a8e000 + 55440
2   libsqlite3.dylib              	       0x1b2a9b890 0x1b2a8e000 + 55440
3   libsqlite3.dylib              	       0x1b2a985bc 0x1b2a8e000 + 42428
4   libsqlite3.dylib              	       0x1b2a97c60 0x1b2a8e000 + 40032
5   libsqlite3.dylib              	       0x1b2a978d8 0x1b2a8e000 + 39128
6   Yatzy.iOS                     	       0x1048fb204 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1077764 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 688268
7   Yatzy.iOS                     	       0x1048fafc8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1077192 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 687696
8   Yatzy.iOS                     	       0x1048fa6c0 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1074880 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 685384
9   Yatzy.iOS                     	       0x1048fa564 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1074532 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 685036
10  Yatzy.iOS                     	       0x10487ada8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 552360 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 162864
11  Yatzy.iOS                     	       0x10487a508 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 550152 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 160656
12  Yatzy.iOS                     	       0x10488247c plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 582780 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 193284
13  Yatzy.iOS                     	       0x1048822b4 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 582324 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 192828
14  Yatzy.iOS                     	       0x104882238 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 582200 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 192704
15  Yatzy.iOS                     	       0x1048837a8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 587688 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 198192
16  libdispatch.dylib             	       0x1960ef4b4 _dispatch_call_block_and_release + 32
17  libdispatch.dylib             	       0x1960f0fdc _dispatch_client_callout + 20
18  libdispatch.dylib             	       0x1960f8694 _dispatch_lane_serial_drain + 672
19  libdispatch.dylib             	       0x1960f91e0 _dispatch_lane_invoke + 384
20  libdispatch.dylib             	       0x196103e10 _dispatch_workloop_worker_thread + 652
21  libsystem_pthread.dylib       	       0x1dc1f5df8 _pthread_wqthread + 288
22  libsystem_pthread.dylib       	       0x1dc1f5b98 start_wqthread + 8

Thread 20:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 21:
0   libdispatch.dylib             	       0x1961161d8 _dispatch_kevent_mach_msg_recv + 128
1   libdispatch.dylib             	       0x196113bb0 _dispatch_event_loop_merge + 148
2   libdispatch.dylib             	       0x196113bb0 _dispatch_event_loop_merge + 148
3   libdispatch.dylib             	       0x196103d10 _dispatch_workloop_worker_thread + 396
4   libsystem_pthread.dylib       	       0x1dc1f5df8 _pthread_wqthread + 288
5   libsystem_pthread.dylib       	       0x1dc1f5b98 start_wqthread + 8

Thread 22:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 26:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 27:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 28:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 29:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 30:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 31 name:   Dispatch queue: com.google.fira.worker
Thread 31:
0   libsystem_platform.dylib      	       0x1dc15fc6c _platform_memset + 108
1   libsqlite3.dylib              	       0x1b2ab884c 0x1b2a8e000 + 174156
2   libsqlite3.dylib              	       0x1b2b4f848 0x1b2a8e000 + 792648
3   libsqlite3.dylib              	       0x1b2ab3288 0x1b2a8e000 + 152200
4   libsqlite3.dylib              	       0x1b2ad3d34 0x1b2a8e000 + 286004
5   libsqlite3.dylib              	       0x1b2ad2690 sqlite3_step + 1296
6   Yatzy.iOS                     	       0x1048fb7b8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1079224 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 689728
7   Yatzy.iOS                     	       0x1048fb6cc plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1078988 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 689492
8   Yatzy.iOS                     	       0x1048f70c8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1061064 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 671568
9   Yatzy.iOS                     	       0x1048747ec plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 526316 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 136820
10  Yatzy.iOS                     	       0x10486a6e8 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 485096 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 95600
11  Yatzy.iOS                     	       0x1048a60f4 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 729332 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 339836
12  Yatzy.iOS                     	       0x1048a5a74 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 727668 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 338172
13  Yatzy.iOS                     	       0x1048a5298 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 725656 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 336160
14  Yatzy.iOS                     	       0x1048a5178 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 725368 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 335872
15  Yatzy.iOS                     	       0x1048f0310 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 1032976 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 643480
16  libdispatch.dylib             	       0x1960ef4b4 _dispatch_call_block_and_release + 32
17  libdispatch.dylib             	       0x1960f0fdc _dispatch_client_callout + 20
18  libdispatch.dylib             	       0x1960f8694 _dispatch_lane_serial_drain + 672
19  libdispatch.dylib             	       0x1960f91e0 _dispatch_lane_invoke + 384
20  libdispatch.dylib             	       0x196103e10 _dispatch_workloop_worker_thread + 652
21  libsystem_pthread.dylib       	       0x1dc1f5df8 _pthread_wqthread + 288
22  libsystem_pthread.dylib       	       0x1dc1f5b98 start_wqthread + 8

Thread 32:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 33:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 34:
0   libsystem_pthread.dylib       	       0x1dc1f5b90 start_wqthread + 0

Thread 35 name:  Thread Pool Worker
Thread 35:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 36 name:  Thread Pool Worker
Thread 36:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 37 name:  Thread Pool Worker
Thread 37:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 38 name:  Thread Pool Worker
Thread 38:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 39 name:  Thread Pool Worker
Thread 39:
0   libsystem_kernel.dylib        	       0x1cbb9aa3c semaphore_timedwait_trap + 8
1   Yatzy.iOS                     	       0x106f04e1c gc.safepoint_poll + 37909516
2   Yatzy.iOS                     	       0x106f103b8 gc.safepoint_poll + 37956008
3   Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
4   libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 40 name:  Timer-Scheduler
Thread 40:
0   libsystem_kernel.dylib        	       0x1cbb9b37c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1dc1fd06c _pthread_cond_wait + 1232
2   Yatzy.iOS                     	       0x106f75004 gc.safepoint_poll + 38368756
3   Yatzy.iOS                     	       0x106f1bae0 gc.safepoint_poll + 38002896
4   Yatzy.iOS                     	       0x106f1b9b8 gc.safepoint_poll + 38002600
5   Yatzy.iOS                     	       0x106f1bbdc gc.safepoint_poll + 38003148
6   Yatzy.iOS                     	       0x106f0a8e4 gc.safepoint_poll + 37932756
7   Yatzy.iOS                     	       0x106e86884 gc.safepoint_poll + 37391988
8   Yatzy.iOS                     	       0x104af0618 gc.safepoint_poll + 76808
9   Yatzy.iOS                     	       0x104ce6ac8 gc.safepoint_poll + 2134200
10  Yatzy.iOS                     	       0x104cdf964 gc.safepoint_poll + 2105172
11  Yatzy.iOS                     	       0x106e08c14 gc.safepoint_poll + 36876804
12  Yatzy.iOS                     	       0x106ec2860 gc.safepoint_poll + 37637712
13  Yatzy.iOS                     	       0x106ec81fc gc.safepoint_poll + 37660652
14  Yatzy.iOS                     	       0x106f104b0 gc.safepoint_poll + 37956256
15  Yatzy.iOS                     	       0x106f1023c gc.safepoint_poll + 37955628
16  libsystem_pthread.dylib       	       0x1dc1f66cc _pthread_start + 148
17  libsystem_pthread.dylib       	       0x1dc1f5ba4 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000016   x5: 0x000000010a30d200   x6: 0x0000000000001000   x7: 0xffffffff00003600
    x8: 0x65e19ba63dc7385e   x9: 0x65e19ba7d91fcf9e  x10: 0x0000000000000259  x11: 0x0000000000000000
   x12: 0x000000010a5d0400  x13: 0x0000000109ce5533  x14: 0x00000000000000e0  x15: 0x0000000080000000
   x16: 0x0000000000000148  x17: 0x00000001e4d8f7c0  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x00000001e4d8f8a0  x22: 0x0000000000000000  x23: 0x000000010a020a00
   x24: 0x0000000109ce5530  x25: 0x000000016b608c80  x26: 0x0000000000000002  x27: 0x000000010742d568
   x28: 0x0000000000ffffff   fp: 0x000000016b607ec0   lr: 0x00000001dc1fc1ac
    sp: 0x000000016b607ea0   pc: 0x00000001cbba1160 cpsr: 0x40000000
   far: 0x0000000101204000  esr: 0x56000080  Address size fault

Binary Images:
       0x1cbb96000 -        0x1cbbd0fe3 libsystem_kernel.dylib arm64e  <9daa5c2993e03768a3e1e139995dc4af> /usr/lib/system/libsystem_kernel.dylib
       0x1dc1f5000 -        0x1dc200fff libsystem_pthread.dylib arm64e  <f2ba7ec0f75a3345b4f6f7da4979b902> /usr/lib/system/libsystem_pthread.dylib
       0x196134000 -        0x1961b3ff7 libsystem_c.dylib arm64e  <f088d98df2a13452996f9e6bb5139f52> /usr/lib/system/libsystem_c.dylib
       0x1047f4000 -        0x107133fff Yatzy.iOS arm64  <b4e4fc0149c0339994afa65044375356> /private/var/containers/Bundle/Application/25DB4695-B7AF-4277-9E2B-4F16DB576C86/Yatzy.iOS.app/Yatzy.iOS
       0x188ed5000 -        0x18981efff Foundation arm64e  <07a92f05d8ec327eab3341db9f77ba16> /System/Library/Frameworks/Foundation.framework/Foundation
       0x18ead8000 -        0x18eebdfff CoreFoundation arm64e  <725e49f4653b39bf9a7a8a3250911ecb> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1c8302000 -        0x1c830afff GraphicsServices arm64e  <5adda888f38735f787a7e01fcb9bb928> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x190cad000 -        0x192498fff UIKitCore arm64e  <59cbc9b530ae396ea269a986640001bc> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1ad355000 -        0x1ad3d808f dyld arm64e  <7b63c57361613b33a3a29944ba59722f> /usr/lib/dyld
       0x1b2a8e000 -        0x1b2c2dffb libsqlite3.dylib arm64e  <8a8dc11714fe307fa65c27cdc08d1c31> /usr/lib/libsqlite3.dylib
       0x1960ed000 -        0x196133fff libdispatch.dylib arm64e  <24db930d870b31ceac69534d7896b4a8> /usr/lib/system/libdispatch.dylib
       0x1dc15f000 -        0x1dc165ff3 libsystem_platform.dylib arm64e  <4bfe8f4751e737b2a2a9a42194239137> /usr/lib/system/libsystem_platform.dylib

EOF

**Comment by marcojak** [comment]
I'm not sure if it's related to the plugin. Try to test it in release mode on your device and see if it works. If possible try the same os and the same device.
It's strange that no one else has raised this issue.
