### ISSUE TITLE
No resource for MobileAds.initialize()

### ISSUE THREAD

**Issue by starlisa** [marcojak/MTAdmob#127]
When I add the code for MobileAds.initialize(), it tells me that it can't find MobileAds.  I'm using MarcTron.AdMob 1.9.0.3, but there are no libraries in the Android app resource folder that contain MobileAds.  Did something fail to install properly?

Thanks,
Lisa

**Comment by ozmertdeniz** [comment]
Hi starlisa, I'm also dealing with the same error, can you explain how you solved it?

**Comment by ozmertdeniz** [comment]
> When I add the code for MobileAds.initialize(), it tells me that it can't find MobileAds. I'm using MarcTron.AdMob 1.9.0.3, but there are no libraries in the Android app resource folder that contain MobileAds. Did something fail to install properly?
> 
> Thanks, Lisa

Hi starlisa, I'm also dealing with the same error, can you explain how you solved it?
