### ISSUE TITLE
Updating to 2.1.0 Crashes Xamarin iOS Project

### ISSUE THREAD

**Issue by PonyOny** [marcojak/MTAdmob#139]
**Describe the bug**
when updating to the latest version it corrupts my iOs project, i can see it adds the following line to XXXX.iOS.csproj.nuget.g.targets

`<Import Project="$(NuGetPackageRoot)xamarin.google.ios.usermessagingplatform\1.1.0.1\buildTransitive\Xamarin.Google.iOS.UserMessagingPlatform.targets" Condition="Exists('$(NuGetPackageRoot)xamarin.google.ios.usermessagingplatform\1.1.0.1\buildTransitive\Xamarin.Google.iOS.UserMessagingPlatform.targets')" />`

this line makes my project not load and shows the following error

>The imported project file "C:\nuget\xamarin.google.ios.usermessagingplatform\1.1.0.1\buildTransitive\Xamarin.Google.iOS.UserMessagingPlatform.targets" could not be loaded. The '_GoogleUserMessagingPlatformAssemblyName' start tag on line 3 position 6 does not match the end tag of '_GoogleMobileAdsAssemblyName'. Line 3, position 132.

**To Reproduce**
Update nuget to version 2.1.0

**Expected behavior**
It should work as normal and not corrupt my iOS project

**Comment by marcojak** [comment]
Hi.

I'm aware of the issue (that is not related directly to the library but to a xamarin plugin) and I'm trying to solve it.
Meanwhile, the solution is this:
Open the file "C:\nuget\xamarin.google.ios.usermessagingplatform\1.1.0.1\buildTransitive\Xamarin.Google.iOS.UserMessagingPlatform.targets"

Replace the line
<_GoogleUserMessagingPlatformAssemblyName>Google.UserMessagingPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</_GoogleMobileAdsAssemblyName>

with

<_GoogleUserMessagingPlatformAssemblyName>Google.UserMessagingPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</_GoogleUserMessagingPlatformAssemblyName>

That will fix the issue!

**Comment by PonyOny** [comment]
That works & project is loaded properly but this is causing issues with AutoFac, if I remove latest version all works as expected.

**Comment by marcojak** [comment]
What issue do you get with AutoFac? Can you post me the log or tell me how
to reproduce it? So I can see if it's an issue with the plugin or not

**Comment by marcojak** [comment]
Yes correct.

**Comment by marcojak** [comment]
Close as not an issue
