### ISSUE TITLE
Problem with Facebook Audience Network mediation.

### ISSUE THREAD

**Issue by RadoslawKubas** [marcojak/MTAdmob#14]
**Describe the bug**
I'm trying to setup Facebook Audience Network mediation. In AdMob configuration panel all seems to be fine, but I don't see Facebook ads in app (AdMob ads works fine). There is error in console

`<Google> Cannot find an ad network adapter with the name(s): GADMAdapterFacebook. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
`

**To Reproduce**
Implement MTAdmob banner in iOS app. Create mediation group in AdMob configuration panel. Facebook ads not appears but there is an error in console.

**Expected behavior**
I believe it may be not exactly plugin problem, just needs to add an additional dependency, but I can't find anything working together with plugin, so any advice would be great. 

Thank you!

**Comment by KrizCologne** [comment]
For ad mediation you need a seperate adapter per network. So in your case you need a adapter for facebook.
look [here](https://stackoverflow.com/questions/48363760/admob-mediation-with-facebook-audience-network-in-xamarin-forms)
