### ISSUE TITLE
Error on iOS: clang exited with code 1

### ISSUE THREAD

**Issue by jb11-repo** [marcojak/MTAdmob#143]
**Describe the bug**
Getting below error when building in VS for Windows and pairing to Mac for the iOS simulator. Works fine with Android emulator.

**To Reproduce**
1. In VS for Windows, Pair to Mac
2. Build on iOS Simulator
3. See error

**Expected behavior**
Maui app builds to iOS simulator

**Additional context**
Pairing to M2 Mac that has Xcode 15.4 installed.

Full error:

> clang++ exited with code 1:ld: in /Users/MyUsername/Library/Caches/Xamarin/mtbs/builds/MyMauiApp/02b2e598cb2d297dae247439d1eb22d4a6d0f9fcdb24b3f87159ce66eb0c1c18/C:/Users/MyUsername /AppData/Local/XamarinBuildDownloadCache/GUsrMess-1.1.0/Frameworks/Release/UserMessagingPlatform.framework/UserMessagingPlatform(UMPView.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/MyUsername /Library/Caches/Xamarin/mtbs/builds/MyMauiApp/02b2e598cb2d297dae247439d1eb22d4a6d0f9fcdb24b3f87159ce66eb0c1c18/C:/Users/MyUsername/AppData/Local/XamarinBuildDownloadCache/GUsrMess-1.1.0/Frameworks/Release/UserMessagingPlatform.framework/UserMessagingPlatform' for architecture arm64clang: error: linker command failed with exit code 1 (use -v to see invocation)

Installed packages:
```
<ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="9.0.2" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.70" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.70" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageReference Include="Plugin.MauiMTAdmob" Version="1.4.5" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
    <PackageReference Include="Xamarin.Google.iOS.MobileAds" Version="8.13.0.3" />
    <PackageReference Include="MT.Xamarin.Google.iOS.UserMessagingPlatform" Version="1.1.0.4" />
</ItemGroup>
```

**Comment by jb11-repo** [comment]
I updated to Version 1.5.1 and now getting different details within clang exited with code 1 error:

> clang exited with code 1:/Users/MyUsername/Library/Caches/Xamarin/mtbs/builds/MyMauiApp/de4cdab6d8db561d3798b42d482d7ad05ba60cdfe5db6fb496a7e8367d234a4f/obj/Debug/net8.0-ios/iossimulator-arm64/nativelibraries/aot-output/x86_64/System.Private.CoreLib.dll.s:127:7: error: out of range literal value.word 0xa9b67bfd      ^/Users/ MyUsername/Library/Caches/Xamarin/mtbs/builds/MyMauiApp/de4cdab6d8db561d3798b42d482d7ad05ba60cdfe5db6fb496a7e8367d234a4f/obj/Debug/net8.0-ios/iossimulator-arm64/nativelibraries/aot-output/x86_64/System.Private.CoreLib.dll.s:128:7: error: out of range literal value.word 0x910003fd      ^/Users/ MyUsername/Library/Caches/Xamarin/mtbs/builds/MyMauiApp/de4cdab6d8db561d3798b42d482d7ad05ba60cdfe5db6fb496a7e8367d234a4f/obj/Debug/net8.0-ios/iossimulator-arm64/nativelibraries/aot-output/x86_64/System.Private.CoreLib.dll.s:129:7: error: out of range literal value.word 0x1000001e      ^/Users/ MyUsername/Library/Caches/Xamarin/mtbs/builds/MyMauiApp/de4cdab6d8db561d3798b42d482d7ad05ba60cdfe5db6fb496a7e8367d234a4f/obj/Debug/net

Updated packages:
```
<ItemGroup>
            <PackageReference Include="CommunityToolkit.Maui" Version="9.0.2" />
            <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.80" />
            <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.80" />
            <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
    <PackageReference Include="Plugin.MauiMTAdmob" Version="1.5.1" />
      </ItemGroup>
 
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
    <PackageReference Include="Xamarin.Google.iOS.MobileAds" Version="8.13.0.3" />
    <PackageReference Include="MT.Xamarin.Google.iOS.UserMessagingPlatform" Version="1.1.0.4" />
  </ItemGroup>
```
Also have these lines in csproj already:
  ```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Debug'">
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup>
    <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
  </PropertyGroup>
```

**Comment by marcojak** [comment]
Hi.

I don't think I've seen this error before (while I've seen the first one).

My first suggestion would be to clean your solution, delete the obj and bin folders (important )and then rebuild your solution.

One other thing, this is the repository for the Xamarin package. As the issue is for the MAUI version, write any issues here:

https://github.com/marcojak/MauiMTAdmob

Thanks

**Comment by jb11-repo** [comment]
Sure, I'll clean & delete those folders, and add the issue into the Maui version

**Comment by jb11-repo** [comment]
Update--cleaning & deleting obj/bin folders got rid of the error
