### ISSUE TITLE
'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider' Error on start

### ISSUE THREAD

**Issue by ScottishRoss** [marcojak/MTAdmob#18]
**Describe the bug**
Java.Lang.RuntimeException: 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Debug
2. The error appears in break mode.

**Expected behaviour**
I expected the application to run and the banner ad to appear on the page selected.

**Screenshots**
N/A. Error message provided.

**Desktop (please complete the following information):**
 - OS: Android
 - Version 9

**Smartphone (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: Android 10

**Comment by marcojak** [comment]
Hi,

Have you tried the test code to see if that works for you?
So you can copy the configuration from there!

Let me know if it works.

Cheers,
Marco

**Comment by ScottishRoss** [comment]
I appear to have fixed this error by making sure the meta-data tags were included with their <application> tags, which I was unaware of initially. That seems to have solved the problem :)
