### ISSUE TITLE
Provide RDP signal for CCPA compliance

### ISSUE THREAD

**Issue by Quax82** [marcojak/MTAdmob#19]
Please provide RDP signal for California Consumer Privacy Act compliance according https://developers.google.com/admob/android/ccpa .

**Comment by marcojak** [comment]
Hi,

I've added the RDP to the new version 1.5.7. 
I've published it and should be online soon.

**Comment by Quax82** [comment]
Hey Marco,

thank you very much for implementing that so fast!

For some reason, I am not able to use it and getting an error message that UseRestrictedDataProcessing wouldn't be available in IMTAdmob (but it is). Any ideas?

Thanks again and best regards,
Jens

**Comment by Quax82** [comment]
Thank you very much :-) 👍
