### ISSUE TITLE
iOS 14 support

### ISSUE THREAD

**Issue by motoko89** [marcojak/MTAdmob#23]
Hello, is there a plan to support new requirements in iOS 14?

https://support.google.com/admob/answer/9997589?hl=en

* Google Mobile Ads SDK for iOS version 7.64 or later
* AppTrackingTransparency
* maybe SKAdNetwork?

**Comment by marcojak** [comment]
Hi,

Sure, of course.
We need to see Xamarin plans to support it, so I can then make the required
changes in the plugin.

I'm sure we will something very soon.
I'm using this library as well so I'll make sure to make it compatible with
the next version of iOS!

Cheers,
Marco

**Comment by stevewinn74** [comment]
Here are a couple of threads on this and a pull that is pending which might help make the changes which I am sure we are all waiting for :)

https://github.com/xamarin/XamarinComponents/issues/931

https://github.com/xamarin/XamarinComponents/pull/935

**Comment by motoko89** [comment]
@stevewinn74 that PR has been open for 2 months and it's only for Android. I don't think it will go to iOS, which is more urgently needed for iOS 14

**Comment by marcojak** [comment]
The new version 1.6.0 is updated to iOS.MobileAds 7.66 that should add compatibility with iOS 14+
