### ISSUE TITLE
Support for Comply with Google Play’s Families Policy using AdMob

### ISSUE THREAD

**Issue by arahmancsd** [marcojak/MTAdmob#25]
I am using MTAdmob for a while and it is really good. However, I find that it is missing Comply with Google Play’s Families Policy using AdMob (https://support.google.com/admob/answer/6223431). Is it possible to include this options as a global options?

**Comment by marcojak** [comment]
Hi Abdul,

This is something I can add to the plugin.
I'm quite busy right now so probably I'll need a bit of time but I can do
that,
If you feel you want to do it, feel free to modify the code and create a
pull request.

Have a good day,
Marco

Il giorno mer 23 set 2020 alle ore 22:12 Abdul Rahman <
notifications@github.com> ha scritto:

**Comment by marcojak** [comment]
Thanks for the pull request.

I've merged it and I'll publish the new version this morning.

Cheers,
Marco

**Comment by arahmancsd** [comment]
Hello, Marco,

Thanks for the update.
You can update the documentation to reflect this change. Otherwise, I can
update it, but I have to do another pull.

Thanks,
Ab
