### ISSUE TITLE
Add Google UMP SDK for Consent

### ISSUE THREAD

**Issue by AndreasReitberger** [marcojak/MTAdmob#29]
**Describe the solution you'd like**
Hi,
first thank you for making ad integration so easy with your plugin.

Google is offering a new "User Messaging Platform" SDK to collect consent. Is there a chance to integrate the SDK into this plugin?
Another user made a good post here: https://github.com/xamarin/XamarinComponents/issues/931#issuecomment-667705158

**Documentation**
[User Messaging Platform (UMP) (Android documentation)](https://developers.google.com/admob/ump/android/quick-start)
[User Messaging Platform (UMP) (IOS documentation)](https://developers.google.com/admob/ump/ios/quick-start)

**Comment by marcojak** [comment]
It's integrated now!
Together with App Open Ads!
And very soon with native ads (finishing the implementation)
