### ISSUE TITLE
Sample project errors on both Android and iOS with latest Xamarin forms (4.3.0.947036)

### ISSUE THREAD

**Issue by dan5602** [marcojak/MTAdmob#3]
**Describe the bug**
Using the latest sample project causes errors on each different platform. 
Android (at runtime) with "Java.Lang.RuntimeException: 'Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: "

iOS with "framework not found GoogleSignIn SampleMTAdmob.iOS linker command failed with exit code 1"			

**To Reproduce**
1. Update clean sample project to latest Xamarin forms (4.3.0.947036)
2. Try to build for android and iOS
3.Andriod fails at runtime - iOS fails at build.
4. See different error on each platform

**Expected behavior**
No errors on each platform (Android and iOS)

**Comment by marcojak** [comment]
Hi @dan5602 ,

Have you installed Xamarin.Google.iOS.SignIn 4.4.0?
After installing MTAdmob it's important to install
Xamarin.Google.iOS.MobileAds (for iOS) and
Xamarin.Google.iOS.SignIn 4.4.0.

You can find more info [here](https://www.xamarinexpert.it/admob-made-easy/)

If you install the packages you will solve the issue.
Let me know if it works.

Cheers,

Marco

**Comment by dan5602** [comment]
Sorry for late reply.....I know this is closed but just in case anyone else looks here....
Installing Xamarin.Google.iOS.SignIn 4.4.0. fixed the issue - thanks for the help!
