### ISSUE TITLE
1.5.8 update doesn't show ads

### ISSUE THREAD

**Issue by c0d3l3ss** [marcojak/MTAdmob#30]
**Describe the bug**
Dear Team,
After final update of 1.5.8 no banner ads show on both ios or android version 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcojak** [comment]
Hi,
I 'm personally using version 1.5.8 and the ads are working fine on Android and iOS.
There are a lot of people using this library and it's working for them as well.
Is it possible that you haven't configured correctly something?

For Apple something changed for the latest version of iOS. 
I'm updating MTAdmob to support these changes.

**Comment by marcojak** [comment]
We are at version 1.6.1.
I'm closing this one as it's not relevant anymore!
