### ISSUE TITLE
iOS app doesn't build, GTMAppAuthFetcherAuthorization error. Android app is fine and running.

### ISSUE THREAD

**Issue by quicoli** [marcojak/MTAdmob#32]
Hello,

For Android it's all fine. For iOS, app doens' build (using Visual Studio for Mac).

I'm using latest version, 1.6.
Added it to my iOS application, added references to Xamarin.Google.iOS.MobileAds 7.66.0 and Xamarin.Google.iOS.SignIn 5.0.2.1. Followed yours instructions to initialize everything, but when  I try to build and run in emulator, I get these errors:

/Users/user184782/Projects/DonegalWeatherChannelApp/src/DWCApp/DWCApp/DWCApp.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: GTMAppAuthFetcherAuthorization. The symbol '_OBJC_CLASS_$_GTMAppAuthFetcherAuthorization' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (DWCApp.iOS)

Would you have any idea or suggestion?

Thanks for time 👍

**Comment by marcojak** [comment]
Do you need the iOS signin library?
It's not required anymore by mtadmob.
Maybe that's the problem.

**Comment by quicoli** [comment]
Thank you for your reply,
I tried that, same error...

**Comment by marcojak** [comment]
I've updated the packages to version 1.6.1.
Try to use that.
I use this plugin in all my projects and they work just fine, I know that thousands of people use this plugin without problems.
Let me know!

**Comment by marcojak** [comment]
I'm closing the issue. If you still have issues on iOS, feel free to open a new issue
