### ISSUE TITLE
'MobileAds.Initialize(Context, string)' is obsolete: 'deprecated'

### ISSUE THREAD

**Issue by AntvissMedia** [marcojak/MTAdmob#33]
**Describe the bug**
Getting this warning when building for Android:

CS0618	'MobileAds.Initialize(Context, string)' is obsolete: 'deprecated'	

Still builds, but might be a problem in the future.

**To Reproduce**

Initialise in MainActivity:
MobileAds.Initialize(ApplicationContext, "ca-app-pub-xxxxxxxxxxxxxxxxxx~xxxxxxxxxxx");

**Comment by marcojak** [comment]
Replace
MobileAds.Initialize(Context, string)
with
MobileAds.Initialize(Context)

in your AndroidMAnifest, remember to add something like:

<application android:label="SampleMTAdmob.Android">
		<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />		
	</application>

Of course remember to use your AppId
