### ISSUE TITLE
iOS SSV issue

### ISSUE THREAD

**Issue by ShadowOfPhantom** [marcojak/MTAdmob#36]
Hi! I use this plugin for showing rewarded ads and everything works great, but I don't receive SSV callbacks from Google if rewarded ad was viewed on iOS. I use the same code for both Android and iOS and also the same callback URI but as far as I can say google doesn't send callbacks at all so I can't reward iOS users for watching. Should I implement something extra for iOS? 

Thanks in advance!

P.S. Test callbacks from AdMob are working properly.

**Comment by marcojak** [comment]
i'm publishing now the version 1.6.1.
I've tested it and it works fine.
The Event to use is OnRewarded! I've checked and it's called correctly

**Comment by ShadowOfPhantom** [comment]
> i'm publishing now the version 1.6.1.
> I've tested it and it works fine.
> The Event to use is OnRewarded! I've checked and it's called correctly

Hi, thank you for your reply! OnRewarded works well, but the issue is about server side verification callback from google that fires when watching is completed.
