### ISSUE TITLE
MobileAds.SharedInstance is null in iOS 14.0

### ISSUE THREAD

**Issue by Karmageddonium** [marcojak/MTAdmob#37]
**Describe the bug**
MobileAds.SharedInstance is null in iOS 14.0

**Screenshots**
![Bug](https://user-images.githubusercontent.com/15961818/105452117-c9760b00-5c8e-11eb-85b2-8b30b191473e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 1st-gen
 - OS: 14.0

**Additional context**
Fails on start with null ref exception
MarcTron.Admob version 1.6.0

**Comment by Karmageddonium** [comment]
Sample from github is not working too on iOS 14
Tried to update all nuget packages - nothing changed

**Comment by marcojak** [comment]
I'm updating the plugin to version 1.6.1.
I've tested the sample code on this version and it works fine!

**Comment by Karmageddonium** [comment]
> I'm updating the plugin to version 1.6.1.
> I've tested the sample code on this version and it works fine!

Updated to 1.6.1
still nothing
ios 14.0 iphone SE 1st gen

Did you changed info.plist someway?

**Comment by marcojak** [comment]
Have you added the app id to you info.plist?

**Comment by Karmageddonium** [comment]
> Have you added the app id to you info.plist?

tried this (this have already worked few months ago, and now stopped)

    <key>GADApplicationIdentifier</key>
    <string>ca-app-pub-3536981221355701~3306599393</string>
    <key>GADIsAdManagerApp</key>
    <true/>

and from official website

<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~1458002511</string>
<key>SKAdNetworkItems</key>
  <array>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>cstr6suwn9.skadnetwork</string>
    </dict>
  </array>

**Comment by Karmageddonium** [comment]
Found a solution:
null appeared only if building with hotreload on windows via visual studio without connection to Mac. 
Tried to build via Mac and it worked properly.

**Comment by marcojak** [comment]
That's great to know.
This explains why for me it was always working fine and I couldn't
replicate the issue.

I'm glad you found the problem!

**Comment by Karmageddonium** [comment]
@marcojak 
I think that this known issue is to be displayed in readme. I have spent a big amount of time to find it out.

**Comment by freezersharp** [comment]
I'm connected from my Windows VS2019 to a MacBook Pro, using the lastest XCode.
I will try to generate the IPA from the Mac.

**Comment by marcojak** [comment]
> I'm connected from my Windows VS2019 to a MacBook Pro, using the lastest XCode.
> I will try to generate the IPA from the Mac.

You can try on the simulator on the mac...it's faster

**Comment by Quax82** [comment]
@marcojak 
Any chance to get this to work with hot reload?
