### ISSUE TITLE
Black Banner and Intertitial 

### ISSUE THREAD

**Issue by melakhvision** [marcojak/MTAdmob#42]
My banner and interstitial are showing but they are just black. The emplacements are showing but it's just black no image or text on the ads

1 - I tested on a real device ( same issue )
2 - I tested on emulator (same thing )

My manifest is : 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="2" android:versionName="1.1" package="com.senegal.galsenstore" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="29" />
	<application android:label="Galsen Store" android:theme="@style/MainTheme">
		<provider android:name="androidx.core.content.FileProvider" android:authorities="com.senegal.galsenstore.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"/>
		</provider>
		<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />
	</application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

My MainActivity.cs
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            MobileAds.Initialize(this);
            LoadApplication(new App());
        }

This is how the ads shows : 

![image](https://user-images.githubusercontent.com/45154979/109181056-cee1dc00-778b-11eb-911d-a99b5a3c2e77.png)
![image](https://user-images.githubusercontent.com/45154979/109181213-f6d13f80-778b-11eb-85bf-5ffaf5c65402.png)

My Nugget : 
 
![image](https://user-images.githubusercontent.com/45154979/109181477-3dbf3500-778c-11eb-944c-1587f6202a61.png)

**Comment by melakhvision** [comment]
Can Anyone help please

**Comment by xshiiiidev** [comment]
That's a normal behavior wait for sometime it will turn back to test ads. Don't worry when you deploy it to the play store and use your real advertising id it will not be black.

**Comment by marcojak** [comment]
@melakhvision did you solve the issue?
I'm closing it for now but feel free to open it if needed
