### ISSUE TITLE
Crashing App on Android Release mode with Linking other than None

### ISSUE THREAD

**Issue by xshiiiidev** [marcojak/MTAdmob#45]
If you create a new project and add this library and set the android options Linking to anything other than None the application will crash when you try to open it.

I read somewhere that this is cause related to AOT? I don't know anything about AOT.

**Comment by xshiiiidev** [comment]
The problem here is if you use the Linking and set it to None the application size is like 40 mb +

**Comment by marcojak** [comment]
I have set linking to "Sdk Assemblies Only" and the app works perfectly.
It could be possible that the problem is with some other plugin

**Comment by marcojak** [comment]
Regarding AOT, I'd suggest you to read this article:
https://www.xamarinexpert.it/how-to-really-speed-up-your-xamarin-forms-apps-for-android/

This will make your app faster!

**Comment by xshiiiidev** [comment]
@marcojak 
Thank again for the reply.

Could you please attached here the sample project testing you did?

What I did before is remove one by one each of the nuget packages and I always get the crash with the library I don't know what I'm doing wrong. 

I tried that testing with the fresh xamarin project.

Will read the AOT you linked thanks a lot!

**Comment by marcojak** [comment]
Unfortunately I cannot attach the sample project, as I tested it on one of my commercial apps.

In general you should never use Nono as Linking as the app size would be too big.
The best option would be Sdk and User assemblies but most of the times it fails and it's very difficult to understand where the problem is, so this is suggested if the size is very important.
The best option is to use "Sdk Assemblies Only"! This should work always

**Comment by xshiiiidev** [comment]
@marcojak 

I tested it again and still crashing I have made a repo [dummy project here](https://github.com/xshiiiidev/dummy-projects).

Could you please test it on your end if it crashes also to you?

Because no matter what I do the produced signed apk with this dummy project is crashing on start up.

**Comment by manonaga2188** [comment]
I'm also facing this issue. Working fine in 1.6.0 But can't in 1.6.1.

**Comment by marcojak** [comment]
I cannot reproduce the issue.
Have you tried with the test project?
