### ISSUE TITLE
Using API 30 Ads is not showing

### ISSUE THREAD

**Issue by xshiiiidev** [marcojak/MTAdmob#46]
When using API 30 the Ads is not showing. The Ads show for API 29 below.

**Comment by marcojak** [comment]
Hi.

I've just checked on my app and the ads are appearing correctly on API 30 as well.

**Comment by xshiiiidev** [comment]
@marcojak 

Thank for the reply.

Can you attached here a sample project you did the testing? I just wanna check if I'm doing something wrong.

Because the Ads is not showing when I changed my target platform to API 30.

Btw, I'm testing this with test Ads.

**Comment by marcojak** [comment]
In this repository in the Sample folder there is the project you can use to test the ads.
That should work fine.
After going to API 30, try to clean the solution, remove the bin & obj folders and build the solution again.
If the ads still don't appear, have a look at the output window, probably it will show the error.

**Comment by xshiiiidev** [comment]
Thanks again @marcojak I will do this.

**Comment by marcojak** [comment]
I'll close for now. If needed, feel free to reopen it
