### ISSUE TITLE
Ad not showing 

### ISSUE THREAD

**Issue by cissemy** [marcojak/MTAdmob#47]
Hi
I added the style to app.xaml but the banner is style not showing : 
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AdmobXam.App">
    <Application.Resources>
        <ResourceDictionary>
            <Style x:Key="admobStyle" TargetType="controls:MTAdView">
                <Setter Property="HeightRequest">
                    <Setter.Value>
                        <x:OnIdiom Phone="50" Tablet="90"/>
                    </Setter.Value>
                </Setter>
            </Style>
        </ResourceDictionary>
          
    </Application.Resources>
</Application>
on my page i have 👍 <?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:controls="clr-namespace:MarcTron.Plugin.Controls;assembly=Plugin.MtAdmob"
             x:Class="AdmobXam.MainPage">

    <StackLayout>

        <controls:MTAdView Style="{StaticResource admobStyle}" IsVisible="true" PersonalizedAds="true" AdsId="myownAdid"/>

        <Label Text="Start developing now" FontSize="Title" Padding="30,10,30,10"/>
        
    </StackLayout>

</ContentPage>
Thanks

**Comment by marcojak** [comment]
Hi Mohamed,
Be sure to use a test Ads Id or to include your phone Id in the test devices.
Almost 100% of the time the ads don't appear as the Admob account is new or the app is not on the store yet.
If you use the test Ids, this doesn't happen and you should be able to see the ads!

**Comment by marciosouzajunior** [comment]
Hi, I had this problem and in my case it was because the emulator system image did not have Google Play.

**Comment by marcojak** [comment]
@cissemy was that the issue?
I'm closing the issue but feel free to open it if needed.
