### ISSUE TITLE
Video interstitials now showing when app was pubished to Google Play

### ISSUE THREAD

**Issue by booooohdan** [marcojak/MTAdmob#49]
**Describe the bug**
Video interstitials (Interstitial with reward. New AdMob feature) now showing when the app was published to Google Play. Regular interstitial worked as well, but video not appearing. My account is valid for more than a year. Both interstitial ads (video and regular) were created more than a week ago. The release of a new version of the app was also more than a week ago. Also, the test id for video interstitial is working.

**To Reproduce**
1. Publish the app with video interstitial to Google Play
2. To see that ads are not appearing

**Expected behavior**
Video interstitial is working

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10

**Comment by booooooogdan** [comment]
I mean Interstitial with reward. New AdMob feature

**Comment by marcojak** [comment]
Do you still have the problem?

I know that sometimes when the Video don't work, you can add this to your AndroidManifest:

<application android:label="SampleMTAdmob.Android" **android:hardwareAccelerated="true"**>

I hope this solves the problem, otherwise let me know.
