### ISSUE TITLE
Sample SecondPage.xml needs small update

### ISSUE THREAD

**Issue by dassick** [marcojak/MTAdmob#50]
Thanks for the good work. After two days of struggling with AdMob, your sample is the first that works for me.
I only had to fix a small detail:

In the sample code, in SecondPage.xaml.cs the NextPage function is missing:
private void NextPage(object sender, EventArgs e)
        {
            DisableEvents();
            Navigation.PushAsync(new SecondPage());
        }

Either that, or the Next Page button should be removed from SecondPage.xaml.

**Comment by marcojak** [comment]
Just checked. In the second page, there is no "Next Page" button so the NextPage function is not needed.
Close it for now.
