### ISSUE TITLE
Adjust the control height according to the size of the Ads

### ISSUE THREAD

**Issue by eyeveye** [marcojak/MTAdmob#53]
**Is your feature request related to a problem? Please describe.**
Now require to fix the height request of the control in order to show the Ads. Unable to adjust the height of the control based on the size of the Ads. I have configure the height of the control is 90, and if the ads only 50, it will show a gap on the screen.

**Describe the solution you'd like**
Able to detect the Ads height and the height of the control will be adjusted.

**Comment by marciosouzajunior** [comment]
I found that ads are shown properly without fixed height after 1 minute when a new request is made. It seems that ads need to be loaded before page appeared on screen. I got this working by using a dirty hack to reset its visible state within AdsLoaded event:

`        private void myAds_AdsLoaded(object sender, EventArgs e)
        {
            myAds.IsVisible = false;
            myAds.IsVisible = true;
        }`

Maybe @marcojak can give us a insight on this.

**Comment by eyeveye** [comment]
How did you make the new request?

**Comment by eyeveye** [comment]
> I found that ads are shown properly without fixed height after 1 minute when a new request is made. It seems that ads need to be loaded before page appeared on screen. I got this working by using a dirty hack to reset its visible state within AdsLoaded event:
> 
> ```
>         private void myAds_AdsLoaded(object sender, EventArgs e)
>         {
>             myAds.IsVisible = false;
>             myAds.IsVisible = true;
>         }
> ```
> 
> Maybe @marcojak can give us a insight on this.

Hey  I have tested your way, and it works!
