### ISSUE TITLE
How does the Interstitial  ads works?

### ISSUE THREAD

**Issue by amasu0728** [marcojak/MTAdmob#57]
Hi, hope your are good,

I have  a question about the Interstitial  ads, Does the id is shared in both Android and IOS, or i have to create the aplicacion in admob console, and if so, how do I implemente the two ids of the Interstitial  ads in xamarin forms using your package.

Thanks

Regards

**Comment by marcojak** [comment]
Hi.
You need to create your app on Admob. One for Android, the other for iOS.
For each app, you have to create an interstitial and use in the plugin the 2 IDs created for you.

**Comment by amasu0728** [comment]
Thanks so much for the response, 

I will try what you said, and anything I let you know
Thanks

Regards.
