### ISSUE TITLE
The plugin is not compatible with the latest Xamarin.GooglePlayServices.Ads.Lite (120.0.0)

### ISSUE THREAD

**Issue by RadoslawKubas** [marcojak/MTAdmob#59]
It's not exactly a bug, but breaking changes in Xamarin.GooglePlayServices.Ads.Lite.

After update from 119.8.0 to 120.0.0 you can't build Android project anymore:

`Unable to resolve interface type 'Android.Gms.Ads.Reward.IRewardedVideoAdListener'. Are you missing an assembly reference?`

**Comment by marcojak** [comment]
Ok, I've seen 3 days ago, they released the new version of the Google play services.

This evening after work, I'll update the plugin to solve any issues with this version

**Comment by marcojak** [comment]
Ok, I've checked and there are many many differences. I'm already working on them but it will require some time.
I hope to have all finished by the end of the week.

**Comment by RadoslawKubas** [comment]
Amazing :) Thank you!

**Comment by RadoslawKubas** [comment]
@marcojak Hello, any news?

**Comment by marcojak** [comment]
Hi. I've been very busy lately on some other projects.
It's quite a big change so it takes some time (but meanwhile it works perfectly fine with the previous version  id the GPlayServices.
I hope to release an update soon

**Comment by RadoslawKubas** [comment]
@marcojak Thanks a lot for the updated info!

**Comment by marcojak** [comment]
@RadoslawKubas just as an update, I've started to work on the next version of the plugin. 
The  Android version is almost completed then I have to work on the iOS version.

**Comment by marcojak** [comment]
The new version is online.
I did some tests and it worked fine.
Let me know if it works for you.

**Comment by RadoslawKubas** [comment]
@marcojak Thank you for update, I will test asap. :)

**Comment by RadoslawKubas** [comment]
Everything seems be be perfect :) Thank you!

**Comment by Quax82** [comment]
Installation working fine now but OnRewarded not firing anymore.
