### ISSUE TITLE
Banner in iOS does not work when app is submit in the App Store

### ISSUE THREAD

**Issue by amasu0728** [marcojak/MTAdmob#60]
Hi, Hope having a good day

I have been having issue with the ads in the iOS,  with Android everything is ok, but when I submit my app in the App Store, the ad banner does not appear, I build the app using an MacBook Pro, and I have no idea what to do more

Please need help with this

Regards

**Comment by marcojak** [comment]
Hi,

Have you tested the app in debug mode before submitting it to the App Store?
Does it work?

Maybe it's a wrong id or something is missing but it's difficult to know
more without additional information

**Comment by amasu0728** [comment]
Hi,
Yes in the debug mode everything works perfect, when I test the app in debug its display test mode using my ids that I configure in the admob panel example in attach picture
![Captura de Pantalla 2021-05-27 a la(s) 12 19 23 p  m](https://user-images.githubusercontent.com/83730639/119869579-03c61200-bee6-11eb-8c8d-5f5edf5e4382.png)

I verify everything the ids but something wrong is happening when I submit the app in the appstore

Something in mind to solve this issue

Thansk

Regards

**Comment by marcojak** [comment]
Is your admob account new or old? Usually Google doesn't immediately send
out real ads but it may need few days to do so. In general if you see the
test ads, it means that everything is configured correctly.

**Comment by amasu0728** [comment]
Thanks for the fast reply,

Maybe I found the issue, it is necessary to download the Xamarin.Google.iOS.MobileAd package in the ios proyect??
or it does not matter ??

Thanks for the replay

Regards.

**Comment by marcojak** [comment]
That should already be included but in case you can add it, anyway it would be strange if it was the problem as I wouldn't understand why the test ads work and the proper ones don't.

**Comment by amasu0728** [comment]
I will let you know if installing that package solve the problem

Thanks

Regards

**Comment by amasu0728** [comment]
Hi Marco, hope your having an excellent day, 

I want to know something about this part of the explanation of the implementation:
**If you are builing your app for iOS on Windows without using your Mac, then MobileAds.SharedInstance will be null and the ads will not work.

You have to build the app using your Mac to use Admob on iOS!**

this part has to be done using a  VS Mac, or it can be done using a VS Windows connected with a Mac?

Hope you can help me with this issue

Thanks

Regards

**Comment by marcojak** [comment]
Sorry to reply just now, I somehow missed your message.

It can be done on a Mac or on Windows connected with a Mac, it doesn't matter, the important thing is that there is a Mac to build the code
