### ISSUE TITLE
Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Ads.InterstitialAd

### ISSUE THREAD

**Issue by AndreasReitberger** [marcojak/MTAdmob#61]
**Describe the bug**
If I build my Android App with Version 1.6.1, get an error (see full log below).

`Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Der Verweis auf "Android.Gms.Ads.InterstitialAd" (definiert in Assembly "Plugin.MtAdmob, Version=1.6.1.0, Culture=neutral, PublicKeyToken=null") mit dem Bereich "Xamarin.GooglePlayServices.Ads.Lite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht aufgelöst werden`

I tried Android 10 and Android 11 as target version, both giving me this issue.
Thanks for looking into this!

**To Reproduce**
1. Update to latest version (your plugin and Xamarin.Firebase.Ads)
2. Click build for Android

**Smartphone (please complete the following information):**
 - OS: Android 10, 11
 - Version 1.6.1

**Additional context**

```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Der Verweis auf "Android.Gms.Ads.InterstitialAd" (definiert in Assembly "Plugin.MtAdmob, Version=1.6.1.0, Culture=neutral, PublicKeyToken=null") mit dem Bereich "Xamarin.GooglePlayServices.Ads.Lite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht aufgelöst werden. Wenn sich der Bereich von der definierenden Assembly unterscheidet, weist dies üblicherweise auf einen weitergeleiteten Typ hin. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Ads.InterstitialAd
   bei Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   bei MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
   bei Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type)
   bei Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   bei Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   bei Mono.Linker.Steps.MarkStep.Initialize()
   bei Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   bei MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   bei Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   bei Mono.Linker.Pipeline.Process(LinkContext context)
   bei MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   bei Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   bei Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:Zeile 17.	3dPrintCostCalculatorLite.Android		
```

**Comment by marcojak** [comment]
Hi,

The reason is that you are using the latest Xamarin.GooglePlayServices.Ads that are not compatible.
Try to use version 119.8.0 or earlier and it will work.

I need to update the plugin to support the new library but there are many changes and it takes time.

**Comment by AndreasReitberger** [comment]
Thanks for the quick reply. Downgrading of the Google ads plugin solved it for now :)

**Comment by actopozipc** [comment]
Had exactly the same error. Disabling the linker works too for the moment, but it produces a different error. Anyway thanks for the real solution and please update it ASAP, took me hours to find

**Comment by AndreasReitberger** [comment]
@marcojak 
Any update on this? Do you have an ETA for updating to the new library?
Thank you,
Andreas

**Comment by marcojak** [comment]
Hi @AndreasReitberger 
I'm working on it and part of the code is already here (in a secondary branch).
I need to do some tests but apparently everything works fine on Android, I need anyway to do some more work on iOS and test it there.
August doesn't help but I'm currently working on it.

**Comment by AndreasReitberger** [comment]
> Hi @AndreasReitberger 
> 
> I'm working on it and part of the code is already here (in a secondary branch).
> 
> I need to do some tests but apparently everything works fine on Android, I need anyway to do some more work on iOS and test it there.
> 
> August doesn't help but I'm currently working on it.

Hi @marcojak 
Thanks for your response. Glas to hear that you are on it.
Thanks a lot for this awesome nuget 👍🏻

**Comment by marcojak** [comment]
The new version is online.
I did some tests and it worked fine.
Let me know if it works for you.

**Comment by AndreasReitberger** [comment]
> The new version is online.
> I did some tests and it worked fine.
> Let me know if it works for you.

Hi, 
just updated to the latest version and figured out that the property `PersonalizedAds` is missing.
Do you have updated docs how set personalized ads true / false with the latest version?

Thank you,
Andreas

**Comment by marcojak** [comment]
Hi Andreas,
Yes I've removed the PersonalizedAds from the AdView, as I thought it was of no use. 
You can anyway set the global property:
CrossMTAdmob.Current.UserPersonalizedAds.
