### ISSUE TITLE
Banner Ads Not Appearing Correctly on Some Android Devices

### ISSUE THREAD

**Issue by srknskr** [marcojak/MTAdmob#63]
**Describe the bug**
AdMob Banner ads appear fine on some devices, while appearing broken on others. I don't think this issue is related to the layout of XAML. Because I only faced this issue on some devices.

**Screenshots**
[Screenshot](https://drive.google.com/file/d/1U0M3K4D7PeF_EPJYVZft3q5uA2s7YnOG/view?usp=sharing)

 - Device: Oppo Reno Z2, Xiaomi Redmi Note 9
 - OS: Android 10

**This is my BannerAd.xaml codes**
`<?xml version="1.0" encoding="UTF-8"?>
<controls:MTAdView  
    xmlns:controls="clr-namespace:MarcTron.Plugin.Controls;assembly=Plugin.MtAdmob"
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="QRScanner.Views.BannerAd"
    x:Name="bannerAd" 
    IsVisible="{Binding IsAdsVisible}"  
    PersonalizedAds="true"
    VerticalOptions="Fill"
    HeightRequest="50"
    AdsId="{OnPlatform Android='BANNER AD IF FOR ANDROID',  iOS='BANNER AD IF FOR IOS"   >
</controls:MTAdView>
`

**Comment by marcojak** [comment]
Are you sure that those devices have the Google Play services installed?
If they don't you'll not see the ads.

**Comment by srknskr** [comment]
Both devices have Google Play services installed. I think this issue might be related to Android version or screen size. Maybe the plugin needs to be updated.

**Comment by marcojak** [comment]
I've updated the plugin.
I'm closing the issue for now but feel free to reopen it if you still have the issue

**Comment by srknskr** [comment]
The problem still exists. As I understand it, 90px banner ads appear on some devices. Just like tablets. As such, the 90px banner ad overflows from the 50px area.

**Comment by onezerotech** [comment]
Yes, above issue still exists.
