### ISSUE TITLE
can't load interstitial ad

### ISSUE THREAD

**Issue by prok155** [marcojak/MTAdmob#68]
**Describe the bug**
Hello. Recently I've updated plugin from 1.6.1 to 1.6.3 version. My app displays rewarded ads and interstitial ads. Rewarded ads work correctly, but when I try to load interstitial ad, I got an error:

`[Ads] Invalid value passed to setMaxAdContentRating: MAX_AD_CONTENT_RATING_G`

I use following configuration:

`
 CrossMTAdmob.Current.TagForChildDirectedTreatment = MTTagForChildDirectedTreatment.TagForChildDirectedTreatmentUnspecified;
            CrossMTAdmob.Current.TagForUnderAgeOfConsent = MTTagForUnderAgeOfConsent.TagForUnderAgeOfConsentUnspecified;
            CrossMTAdmob.Current.MaxAdContentRating = MTMaxAdContentRating.MaxAdContentRatingG;
`

**To Reproduce**
1. Load interstitial ad
2. The ad didn't load, and visual studio displays `[Ads] Invalid value passed to setMaxAdContentRating: MAX_AD_CONTENT_RATING_G`

**Expected behavior**
Interstitial ads load and display correctly.

**Comment by marcojak** [comment]
@prok155 Android or iOS?

**Comment by prok155** [comment]
Android
Plugin Version: 1.6.3
SDK: 30  

Interstitials doesn't load and display in debug/release mode. On ios everything works fine.

**Comment by marcojak** [comment]
I've tried with the demo app and it worked fine.
The string seems valid and the google website gives the same strings:
https://developers.google.com/admob/android/targeting

Can you try with the demo app and tell me if it works for you?

**Comment by prok155** [comment]
I decided to create new project and check it, but it also doesnt work.  I thought that maybe some dependencies cause this issue. I used strings from google and then from my admob account, but both displays following message:

`[Ads] Invalid value passed to setMaxAdContentRating: MAX_AD_CONTENT_RATING_G`


**To Reproduce**
Steps to reproduce the behavior:
1. Create new project, install your package
2. In MainActivity, add `  MobileAds.Initialize(this);`
3. In Manifest, add:
`  <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3940256099942544~3347511713" />
      <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
      <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />`
4. I created button and when I click it, it should show the ad. My code:
`
 private void Button_Clicked(object sender, EventArgs e)
        {
            if (CrossMTAdmob.Current.IsInterstitialLoaded() == false)
                CrossMTAdmob.Current.LoadInterstitial("ca-app-pub-3940256099942544/1033173712");
            else
                CrossMTAdmob.Current.ShowInterstitial();
        }
`


The steps above should display interstitial ads, but it still show `[Ads] Invalid value passed to setMaxAdContentRating: MAX_AD_CONTENT_RATING_G` message. Maybe I miss something and I should install more packages with your plugin?

**Comment by marcojak** [comment]
I've seen in the output Windows the warning message:
[Ads] Invalid value passed to setMaxAdContentRating: MAX_AD_CONTENT_RATING_G

but I can still see the Interstitial and the ads is loaded correctly.

I'll try to see why the string is not valid

**Comment by marcojak** [comment]
Found the issue.
Google documentation wasn't great so I used the wrong strings.

In the version 1.6.4 the problem has been solved!
