### ISSUE TITLE
Problems with rewarded video ads

### ISSUE THREAD

**Issue by randmis** [marcojak/MTAdmob#69]
**Describe the bug**

1) Rewarded video ads (30 seconds) are saying that you can receive the reward after 5 seconds, but this isn’t true, you have to watch the 30 second ad to receive the reward using the completion event trigger.

2) Rewarded video ads are showing 5 second ads. These ads do not provide the reward using the completion event trigger.

**To Reproduce**
1. Load interstitial, show it (repeat this step a few times, sometimes it doesn't occur on first try)
2. I updated the plugin to the latest version and the issue is still present

**Expected behavior**
The completed rewarded ad trigger should work regardless of how long the ad is, if 30 second ads say you can receive the reward after 5 seconds then this should work with the completed rewarded ad trigger

**Smartphone**
 This issue is device agnostic and appears on every device tested

**Additional context**
Testers experience the issue regardless of their device / location

**Comment by marcojak** [comment]
Hi, I'm not sure which one should be the correct behaviour, but you should ask this directly to Google as this is not the plugin responsibility. The plugin just allows to use the native Admob, doesn't decide when to trigger an event.

**Comment by randmis** [comment]
Hi I have just noticed that **since upgrading to the latest version 1.6.4** (along with the Google Admob libraries to 120.2.0 the rewarded video completion event (OnRewardedVideoAdCompleted) in fact **no longer works at all**. To validate this, I downgraded the version back to 1.6.1 and 119.6.0 for Google Admob and OnRewardedVideoAdCompleted has started working again with no changes to the code. So there appears to be some problem with the plugin in the latest version.

**Comment by Quax82** [comment]
I can also comfirm and reproduce this. The OnRewarded event isn't fired anymore in version 1.6.4 together with Google libraries 120.2

**Comment by marcojak** [comment]
I'm testing it right now and I'll update the library if needed

**Comment by marcojak** [comment]
I've just uploaded version 1.6.5.
Small regression in the code. 

The correct method to check the reward is **OnRewarded**

**Comment by Quax82** [comment]
Hi Marco,
thanks for the quick fix. I tested it and it works for me.
Great work!

**Comment by randmis** [comment]
Hi Marco, thank you so much for the fix and for clarifying about the rewarded ads completion event! Everything appears to be working properly now
