### ISSUE TITLE
Space on Android

### ISSUE THREAD

**Issue by Sebastien-Remy** [marcojak/MTAdmob#7]
I have this log on console output on Android devices. It's works fine on iOS.

`Not enough space to show ad. Needs 411x49 dp, but only has 371x49 dp.`

Any idea?

ps: Thank you for you amazing job and stay safe!

**Comment by marcojak** [comment]
Hi Sebastien,
Yes, if you have this issue, you can simply increase the required space setting the HeightRequest on the admob view.
Let me know if this helps you.
