### ISSUE TITLE
I want to contribute advertising for uwp but I can't publish it quickly

### ISSUE THREAD

**Issue by LyVanBong** [marcojak/MTAdmob#71]
![image](https://user-images.githubusercontent.com/87922239/133314590-a4863431-e212-405c-97cd-b987c1235aa9.png)

**Comment by marcojak** [comment]
Hi Ly,

thanks for this, every contribution is always great.

The correct way to contribute on GitHub is the following and you need to:

- fork this project, 
- do the changes
- push the changes to your fork on GitHub
- From your fork open a pull request

I hope this helps but any questions, please let me know.
