### ISSUE TITLE
Large Banner (320 x 100) is showing instead of (320 x 50) in Android

### ISSUE THREAD

**Issue by onezerotech** [marcojak/MTAdmob#72]
**Describe the bug**
AdMob Banner ads are appeared to be broken in most of the devices. It is showing 320 x 100 size Ads though the Admob height is set as 50.

**Expected behavior**
Admob Banner should show 320 x 50 px size Ads.

**Smartphone**
 - Device: Samsung S8, Samsung 20 plus, Samsung M30
 - OS: Android 10, Android 11

**Comment by ShadowOfPhantom** [comment]
Hi! I noticed that I have a similar issue with banners. Sometimes I'm watching my app reviews on YouTube and see that banners on some devices are cropped :О My real devices are fine with it but I just ran simulator and see the same (I attached screenshots)
How to fix this?

![image](https://user-images.githubusercontent.com/41395390/134589455-bfc8eef4-0a91-42bc-9dd5-eb8e68455448.png)

![image](https://user-images.githubusercontent.com/41395390/134588937-d7680485-849e-4c83-9dab-e11a3f4fafcf.png)

**Comment by ShadowOfPhantom** [comment]
I use <Style TargetType="controls:MTAdView">
                <Setter Property="HeightRequest">
                    <Setter.Value>
                        <x:OnIdiom Phone="50" Tablet="90" />
                    </Setter.Value>
                </Setter>
            </Style>
            
            And the fix is to use 90 for both tablet and phone:
            
            
![image](https://user-images.githubusercontent.com/41395390/134589874-26a7dd75-5113-43e6-b3f1-31058c28ac19.png)

But it's a kind of incorrect
Any ideas? :)

**Comment by onezerotech** [comment]
If I delete the Style, it won't show the Ad at all. Should be a fix in this plugin. Google AdMob recommends `SmartBanner` options. Not sure whether that the options used in this plugin.

**Comment by onezerotech** [comment]
@ShadowOfPhantom how did you fix this? your approach didn't solve my problem.

**Comment by onezerotech** [comment]
@marcojak Any update on this issue? Appreciate if you could look into this.

**Comment by roswer13** [comment]
@marcojak @ShadowOfPhantom @onezerotech SmartBanner is deprecated. I creted a pull request for this isseus. I hope it will help.

**Comment by marcojak** [comment]
Thank you very much.

I'll quickly have a look at the code and I'll merge it, possibly together
with few changes I've done.

Thanks again.

Cheers,
Marco
