### ISSUE TITLE
OnRewardedVideoAdLoaded doesn't work anymore

### ISSUE THREAD

**Issue by ShadowOfPhantom** [marcojak/MTAdmob#75]
CrossMTAdmob.Current.OnRewardedVideoAdLoaded += Current_OnRewardedVideoAdLoaded;

Current_OnRewardedVideoAdLoaded doesn't trigger when rewarded ad is loaded on current plugin version (1.6.5). I downgraded it back to 1.6.1 and it works well as always.
Please, check this out

**Comment by marcojak** [comment]
I'll have a look and release a new version if there is a problem (in the new version many things changed and some methods are not supported anymore because replaced by others.

**Comment by ShadowOfPhantom** [comment]
> I'll have a look and release a new version if there is a problem (in the new version many things changed and some methods are not supported anymore because replaced by others.

Appreciate 🙏

**Comment by Junior-OliveiraDeveloper** [comment]
@ShadowOfPhantom can i occupy some of your time? My downgrade failed, it has some errors. Remember when you did this if it was necessary to downgrade some dependency?

**Comment by ShadowOfPhantom** [comment]
> @ShadowOfPhantom can i occupy some of your time? My downgrade failed, it has some errors. Remember when you did this if it was necessary to downgrade some dependency?

Sure!
No, I didn't downgrade something else, I just installed 1.6.1 for all projects through nuget package manager. What kind of errors there?

**Comment by Junior-OliveiraDeveloper** [comment]
Sorry for the inconvenience, deleting the bin and obj folders solved the problem.

**Comment by dmitriikifit** [comment]
OnRewardedVideoAdLoaded  does not work for me as well.

**Comment by marcojak** [comment]
I'm checking and if it doesn't work I'll release a new version

**Comment by marcojak** [comment]
Thanks for letting me know. I'll fix it as well

**Comment by marcojak** [comment]
Version 1.6.7 is online and fixes the OnRewardedVideoAdCompleted on Android

**Comment by ShadowOfPhantom** [comment]
> Version 1.6.7 is online and fixes the OnRewardedVideoAdCompleted on Android

Thank you! 😍

**Comment by roswer13** [comment]
I have downloaded version 1.6.7 in my project and for Android I get the error "java.exe exit code 1", but with version 1.6.6.6 it works correctly, with the inconvenience that the event does not work. I have downgraded again to version 1.6.1.
