### ISSUE TITLE
OnRewardedVideoAdFailedToLoad Doesn't fire

### ISSUE THREAD

**Issue by KognitysPlayhouse** [marcojak/MTAdmob#80]
**Describe the bug**
OnRewardedVideoAdFailedToLoad event doesn't fire if it hits a code 3 error.

**To Reproduce**
1. Attempt to load an ad with admob level ad serving limit (on the console set a limit for X ads per X TIMEPERIOD) I did 5 ads per 10 minutes.
2. Sit through 5 test ads (or however many you set it to)
3. Attempt to load ad
4. See error "[Ads] Ad failed to load : 3"

**Expected behavior**
FailedToLoad event should fire. But it doesn't.

**Comment by KognitysPlayhouse** [comment]
Update it seems to not work only on Android, the iOS version works just fine.

**Comment by KognitysPlayhouse** [comment]
I updated to 1.6.8 and it is still the case, where it doesn't fire the event.

**Comment by marcojak** [comment]
Right now on Android you can use "OnRewardFailedToShow".
In the next version I'll enable "OnRewardedVideoAdFailedToLoad" for Android as well.

**Comment by marcojak** [comment]
The new version 1.6.9 should be online in few minutes and it fixes this issue.

**Comment by KognitysPlayhouse** [comment]
I am not sure if this is just a test device issue or not but, when I am testing for the OnRewardedVideoAdFailedToLoad event it still doesn't work and I get a large Java error in the debugging console. Hopefully, if I load a build on my phone it'll work but I am not too sure what's going on. Here is the log, hope it helps. Or if someone can tell me if this is my issue too that would help.

https://pastebin.com/4DNpLjWP

**Comment by KognitysPlayhouse** [comment]
For clarification the event still doesn't fire.
