### ISSUE TITLE
OnRewardedVideoAdClosed is not fired

### ISSUE THREAD

**Issue by dmitriikifit** [marcojak/MTAdmob#83]
Trying to wait while ads shown and closed and then execute code i need but this event is not firing on Android phone.

**Comment by marcojak** [comment]
Hi,

Right now the implementation on Android is a bit different and you can use: "OnRewardClosed".

In the next version, I'll enable "OnRewardedVideoAdClosed" for Android as well.

**Comment by marcojak** [comment]
The new version 1.6.9 should be online in few minutes and it fixes this issue.
