### ISSUE TITLE
Please clarify what does LoadRewardedVideo() and ShowRewardedVideo() means?

### ISSUE THREAD

**Issue by azrinsani** [marcojak/MTAdmob#87]
I'm still trying to get this to work. No rewarded ads are coming out.

In the meanwhile appreciate if you can clarify what the following means in the docs.

Thanks for the good initiative!

**Comment by marcojak** [comment]
Have you tried to use test IDs?
You will not see any ads during development unless you are using test IDs.

LoadRewardedVideo: The plugin will load the rewarded video. You must call this method before showing a video.
ShowRewardedVideo: The plugin will show the video previously loaded. If the video is not available (eg. you haven't loaded it), the plugin will not show it.

I hope it helps. 
Any questions, let me know.
