### ISSUE TITLE
Ads suddenly stopped showing with "Ad failed to load : 3" - tried using test ads and the same error

### ISSUE THREAD

**Issue by roguedev1** [marcojak/MTAdmob#92]
**Describe the bug**
My ad implementation has been working fine for several months - suddenly in early Jan I stopped receiving impressions despite not having updated my app for several months. I recently noticed and upon checking I am now receiving the message "Ad failed to load : 3". What makes me think this is a problem with MTAdmob is that I tried using test ads (with Google's test ad ID) and the same error happens, which makes no sense as this is the error based on Admob not having ad inventory.

**To Reproduce**
1. Initialise ads as normal - I am using MTAdmob v1.6.9
2. Try to load any ad (rewarded, interstitial, etc.)
3. Receive error message

**Expected behavior**
My ads have been working for months so the expected behaviour is that this would have continued

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android
 - Version 10

**Comment by marcojak** [comment]
Hi,

The code error 3 is:
The ad request was successful, but no ad was returned due to lack of ad inventory.

There is nothing wrong with your code or the plugin, just Google cannot always provide an ad for each request.

Try to have a look at this page to see if you have configured everything correctly: https://developers.google.com/admob/android/test-ads

**Comment by roguedev1** [comment]
Hi thanks for the fast reply, I have tested using Google's demo rewarded ad unit, ca-app-pub-3940256099942544/5224354917 (as shown in your link), therefore how is it possible that Google cannot provide the ad?

**Comment by marcojak** [comment]
Have you tried to use the emulator? If I remember correctly, all the ads there are considered test ads.

Also, if you don't do it already, add your phone id in your list of test devices. this will ensure that you'll only get test ads on that phone.

**Comment by roguedev1** [comment]
Yep my phone ID is in the list of test devices. 

I have just tried using the emulator and it has the same error. It literally has the following code in the debug:

[Ads] This request is sent from a test device.
[Ads] Ad failed to load : 3

**Comment by roguedev1** [comment]
After a lot of searching I realised that I had to check the Google Adsense interface rather than Google Admob. Upon checking the tool I saw I had an alert to verify my identity that did not appear on Admob. Upon verifying the ads have resumed working.
