### ISSUE TITLE
Ads don't show after download from google play store

### ISSUE THREAD

**Issue by parsa4387** [marcojak/MTAdmob#93]
Hi
I built an App with Xamarin Forms and created an in-app ad . During the initial test, the ad is played without any problems, but when I upload it to the Google Play Store, after downloading and installing it from Google Play, the App does not run!

I also got the Ad Unit and App ID from Google Admob and tested with it, but like the last time, after installing and running from Google Play, the App hangs and exits the App automatically.

Would you please tell me where the problem might be?

**Comment by marcojak** [comment]
Hi.
If the app run in debug and not in release, probably there is a problem with the linker.
What setting are you using for that?

I doubt this is an issue with plugin itself.

**Comment by parsa4387** [comment]
I used  "Sdk Assemblis only" for linker. 

Another Options :    bundle Package Format    -    dex Compiler = d8    -    Code shrinker = r8

**Comment by marcojak** [comment]
Mhhh, then it shouldn't be the issue.
Have you tried to run your app on your phone in release mode?

**Comment by ezyweds** [comment]
We were facing same issue, please add "Xamarin.GooglePlayServices.Ads.Lite" in Skip Linking Assemblies,
![image](https://user-images.githubusercontent.com/96765012/153810260-20879947-4f70-4bac-ba3b-d15322db995c.png)

This resolved issue for us

**Comment by parsa4387** [comment]
> We were facing same issue, please add "Xamarin.GooglePlayServices.Ads.Lite" in Skip Linking Assemblies, ![image](https://user-images.githubusercontent.com/96765012/153810260-20879947-4f70-4bac-ba3b-d15322db995c.png)
> 
> This resolved issue for us

I did it But after uploading the app on the Play Store, the app did not run again and the following email was sent to me:


**Exceptions
java.lang.RuntimeException: Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar" ...
.
.
.
.**




Did this problem occur to you? Do you have a suggestion for this problem?

**Comment by ezyweds** [comment]
Try removing R8 code shrinker -Similar Issues reported by few others #58 and #82

**Comment by parsa4387** [comment]
Thanks. That worked

**Comment by marcojak** [comment]
Solved. See issue #98
