### ISSUE TITLE
Rewarded interstitials

### ISSUE THREAD

**Issue by roguedev1** [marcojak/MTAdmob#94]
Hi I couldn't find info on this in the readme - are rewarded interstitials currently supported? Will they be in the future?

**Comment by PonyOny** [comment]
I think this is what you are looking for.

> Rewarded video
You can show a Rewarded video with a single line of code:
**CrossMTAdmob.Current.ShowRewardedVideo();**
To Load a Rewarded Video you can use this line:
**CrossMTAdmob.Current.LoadRewardedVideo("xx-xxx-xxx-xxxxxxxxxxxxxxxxx/xxxxxxxxxx");**

**Comment by roguedev1** [comment]
Thank you!

**Comment by marcojak** [comment]
They are now supported in version 1.9

**Comment by tonyfonager** [comment]
I am using the newest version, but I get this in the debug window : "Rewarded interstitial not fully implemented yet!"
