### ISSUE TITLE
Code sample for implementation in apps for everyone, including children and families

### ISSUE THREAD

**Issue by parsa4387** [marcojak/MTAdmob#99]
Hi

I have created an app whose main audience is children and I have also used your plugin to play ads in this app. I wanted to know if there is any code or settings in your plugin for children (for "Families Ads Program" - "Designed for Families")

**Comment by arahmancsd** [comment]
Please have a look at [Support for Comply with Google Play’s Families Policy using AdMob](https://github.com/marcojak/MTAdmob/issues/25)
